### ISSUE TITLE
AdvertisingIdTask crash on Huawei devices

### ISSUE THREAD

**Issue by jaroslavhavelik** [adform/adform-tracking-android-sdk#12]
After updating to version 1.4.0 or 2.1.0 our clients app is crashing instantly after first tracking point is triggered with following stack trace / message:

```
Caused by java.lang.IllegalStateException: The meta-data tag in your app's AndroidManifest.xml does not have the right value.  Expected 12451000 but found 4323000.  You must have the following declaration within the <application> element:     <meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />
       at com.google.android.gms.common.GooglePlayServicesUtilLight.isGooglePlayServicesAvailable(GooglePlayServicesUtilLight.java:19)
       at com.google.android.gms.common.GoogleApiAvailabilityLight.isGooglePlayServicesAvailable(GoogleApiAvailabilityLight.java:5)
       at com.google.android.gms.ads.identifier.AdvertisingIdClient.a(AdvertisingIdClient.java:17)
       at com.google.android.gms.ads.identifier.AdvertisingIdClient.b(AdvertisingIdClient.java:17)
       at com.google.android.gms.ads.identifier.AdvertisingIdClient.a(AdvertisingIdClient.java:47)
       at com.adform.adformtrackingsdk.services.AdvertisingIdTask.doInBackground(AdvertisingIdTask.java:48)
       at com.adform.adformtrackingsdk.services.AdvertisingIdTask.doInBackground(AdvertisingIdTask.java:21)
       at android.os.AsyncTask$2.call(AsyncTask.java:334)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:246)
       at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:784)
```

This happens only on Huawei devices with Android 8+, we have tried to add metatag (did not helped):
```
<meta-data
    android:name="com.google.android.gms.version"
    android:value="@integer/google_play_services_version" />
```

Any advice?

**Comment by rprunskas** [comment]
Do you add Google Play Services library additionally? Adform Tracking SDK 2.1.0 already comes with Google Play Services Ads 19.1.0, so you should not use any other version of Google Play Services. Also please check maybe one of you libraries uses older Google Play Services version.

**Comment by jaroslavhavelik** [comment]
Seems to work with latest Adds version, thanks for help
