### ISSUE TITLE
Protobuf-lite clashing with protobuf-javalite

### ISSUE THREAD

**Issue by skalajan** [adform/adform-tracking-android-sdk#13]
Hi, I'm using the latest version 2.1.0 of the SDK and have clashing Protobuf dependency with Firebase Config 19.2.0 - 

`Duplicate class com.google.protobuf.AbstractMessageLite found in modules jetified-protobuf-javalite-3.11.0.jar (com.google.protobuf:protobuf-javalite:3.11.0) and jetified-protobuf-lite-3.0.1.jar (com.google.protobuf:protobuf-lite:3.0.1)
`

Could you please update the version of protobuf-javalite (renamed from protobuf-lite)

`com.google.protobuf:protobuf-javalite:3.11.0`

Thank you!

**Comment by gotev** [comment]
Same problem, too using latest Firebase release. See: https://github.com/firebase/firebase-android-sdk/issues/1152

I've tried to solve it like this:

```groovy
implementation ("com.adform.tracking.sdk:adform-tracking-sdk:2.1.0") {
    exclude group: 'com.google.protobuf', module: 'protobuf-lite'
}
```

But then the following exception gets thrown on App startup, which makes the app crash:
```
08-05 17:17:33.113 5033-5033/? E/App$setupExceptionHandl: FATAL EXCEPTION. Thread: main
    java.lang.ExceptionInInitializerError
        at com.adform.adformtrackingsdk.web.ProtobufBuilder.createDeviceDataBuilder(ProtobufBuilder.java:240)
        at com.adform.adformtrackingsdk.web.ProtobufBuilder.buildAsProtoBuf(ProtobufBuilder.java:76)
        at com.adform.adformtrackingsdk.web.NetworkLoader.load(NetworkLoader.java:77)
        at com.adform.adformtrackingsdk.services.SendService.startingSend(SendService.java:112)
        at com.adform.adformtrackingsdk.services.SendService$2.run(SendService.java:149)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5254)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
     Caused by: java.lang.RuntimeException: Unable to get message info for com.adform.mobile.contracts.tracking.DeviceDataContract$DeviceData
        at com.google.protobuf.GeneratedMessageInfoFactory.messageInfoFor(GeneratedMessageInfoFactory.java:62)
        at com.google.protobuf.ManifestSchemaFactory$CompositeMessageInfoFactory.messageInfoFor(ManifestSchemaFactory.java:143)
        at com.google.protobuf.ManifestSchemaFactory.createSchema(ManifestSchemaFactory.java:55)
        at com.google.protobuf.Protobuf.schemaFor(Protobuf.java:93)
        at com.google.protobuf.Protobuf.schemaFor(Protobuf.java:107)
        at com.google.protobuf.GeneratedMessageLite.makeImmutable(GeneratedMessageLite.java:171)
        at com.adform.mobile.contracts.tracking.DeviceDataContract$DeviceData.<clinit>(DeviceDataContract.java:923)
        at com.adform.adformtrackingsdk.web.ProtobufBuilder.createDeviceDataBuilder(ProtobufBuilder.java:240) 
        at com.adform.adformtrackingsdk.web.ProtobufBuilder.buildAsProtoBuf(ProtobufBuilder.java:76) 
        at com.adform.adformtrackingsdk.web.NetworkLoader.load(NetworkLoader.java:77) 
        at com.adform.adformtrackingsdk.services.SendService.startingSend(SendService.java:112) 
        at com.adform.adformtrackingsdk.services.SendService$2.run(SendService.java:149) 
        at android.os.Handler.handleCallback(Handler.java:739) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5254) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
     Caused by: java.lang.UnsupportedOperationException
        at com.adform.mobile.contracts.tracking.DeviceDataContract$DeviceData.dynamicMethod(DeviceDataContract.java:915)
        at com.google.protobuf.GeneratedMessageLite.dynamicMethod(GeneratedMessageLite.java:252)
        at com.google.protobuf.GeneratedMessageLite.buildMessageInfo(GeneratedMessageLite.java:280)
        at com.google.protobuf.GeneratedMessageInfoFactory.messageInfoFor(GeneratedMessageInfoFactory.java:60)
        at com.google.protobuf.ManifestSchemaFactory$CompositeMessageInfoFactory.messageInfoFor(ManifestSchemaFactory.java:143) 
        at com.google.protobuf.ManifestSchemaFactory.createSchema(ManifestSchemaFactory.java:55) 
        at com.google.protobuf.Protobuf.schemaFor(Protobuf.java:93) 
        at com.google.protobuf.Protobuf.schemaFor(Protobuf.java:107) 
        at com.google.protobuf.GeneratedMessageLite.makeImmutable(GeneratedMessageLite.java:171) 
        at com.adform.mobile.contracts.tracking.DeviceDataContract$DeviceData.<clinit>(DeviceDataContract.java:923) 
        at com.adform.adformtrackingsdk.web.ProtobufBuilder.createDeviceDataBuilder(ProtobufBuilder.java:240) 
        at com.adform.adformtrackingsdk.web.ProtobufBuilder.buildAsProtoBuf(ProtobufBuilder.java:76) 
        at com.adform.adformtrackingsdk.web.NetworkLoader.load(NetworkLoader.java:77) 
        at com.adform.adformtrackingsdk.services.SendService.startingSend(SendService.java:112) 
        at com.adform.adformtrackingsdk.services.SendService$2.run(SendService.java:149) 
        at android.os.Handler.handleCallback(Handler.java:739) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5254) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
```

**Comment by rprunskas** [comment]
We updated protobuf in 2.2.0 version.
