### ISSUE TITLE
SecurityException: getDataNetworkTypeForSubscriber on Android 11

### ISSUE THREAD

**Issue by mcatta** [adform/adform-tracking-android-sdk#14]
Hi,
we discovered an incompatibility with Android 11 with the latest version of the `adform-tracking library`. 

**Conditions**
- Project compiled with API version: 30
- The user should use mobile data (not the Wifi)

this because with android 11 to use the `android.permission.READ_PHONE_STATE` we need to ask the user permission. Can we avoid this crash if the permission is not granted? Below the stack trace

```
    java.lang.SecurityException: getDataNetworkTypeForSubscriber
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
        at android.os.Parcel.createException(Parcel.java:2357)
        at android.os.Parcel.readException(Parcel.java:2340)
        at android.os.Parcel.readException(Parcel.java:2282)
        at com.android.internal.telephony.ITelephony$Stub$Proxy.getNetworkTypeForSubscriber(ITelephony.java:8762)
        at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:3021)
        at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:2985)
        at com.adform.adformtrackingsdk.utils.NetworkUtils.getCurrentNetworkStatus(NetworkUtils.java:74)
        at com.adform.adformtrackingsdk.utils.NetworkUtils.getOpenRTBConnectionStatus(NetworkUtils.java:53)
        at com.adform.adformtrackingsdk.web.NetworkLoader.createDeviceData(NetworkLoader.java:109)
        at com.adform.adformtrackingsdk.web.NetworkLoader.load(NetworkLoader.java:68)
        at com.adform.adformtrackingsdk.services.SendService.startingSend(SendService.java:112)
        at com.adform.adformtrackingsdk.services.SendService$2.run(SendService.java:149)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by rprunskas** [comment]
Hi, we added checking for READ_PHONE_STATE permission, update is in 2.3.1 version. Thanks for reporting issue.

**Comment by MATSGAME** [comment]
Is there any solution? I have same problem.
