### ISSUE TITLE
Crash on Android 11: java.lang.ArrayIndexOutOfBoundsException: length=7; index=7 

### ISSUE THREAD

**Issue by mcatta** [adform/adform-tracking-android-sdk#15]
Thank you for the fix on https://github.com/adform/adform-tracking-android-sdk/issues/14 , but it has generated a new one, in the same condition if the permission is not granted the app crashes with this stack:

```
java.lang.ArrayIndexOutOfBoundsException: length=7; index=7
        at com.google.protobuf.MessageSchema.newSchemaForRawMessageInfo(MessageSchema.java:507)
        at com.google.protobuf.MessageSchema.newSchema(MessageSchema.java:227)
        at com.google.protobuf.ManifestSchemaFactory.newSchema(ManifestSchemaFactory.java:77)
        at com.google.protobuf.ManifestSchemaFactory.createSchema(ManifestSchemaFactory.java:71)
        at com.google.protobuf.Protobuf.schemaFor(Protobuf.java:93)
        at com.google.protobuf.Protobuf.schemaFor(Protobuf.java:107)
        at com.google.protobuf.GeneratedMessageLite.makeImmutable(GeneratedMessageLite.java:175)
        at com.google.protobuf.GeneratedMessageLite$Builder.buildPartial(GeneratedMessageLite.java:395)
        at com.google.protobuf.GeneratedMessageLite$Builder.build(GeneratedMessageLite.java:403)
        at com.adform.adformtrackingsdk.web.ProtobufBuilder.buildAsProtoBuf(ProtobufBuilder.java:94)
        at com.adform.adformtrackingsdk.web.NetworkLoader.load(NetworkLoader.java:85)
        at com.adform.adformtrackingsdk.services.SendService.startingSend(SendService.java:120)
        at com.adform.adformtrackingsdk.services.SendService$2.run(SendService.java:158)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

Could be related to `DeviceData`class? Because I noticed that if the permission is not granted the AdForm doesn't add this parameter `deviceData.setConnectionType`.

Thank you in advance, let me know if I can help you

**Comment by rprunskas** [comment]
Hello, this crash is not related to DeviceData class. It seems your app or one of your app the libraries uses newest protobuf version - 3.13.0. Our SDK was tested just with 3.11.0, please try to downgrade protobuf until we find solution or maybe it's protobuf bug. If you need any help for downgrading protobuf please don't hesitate to ask .

**Comment by mcatta** [comment]
Hi, It works, I downgraded our protobuf library to 3.11.0.

Thank you again for the help I close the issue.

**Comment by rprunskas** [comment]
We updated protobuf library to 3.13.0 in 2.4.0 SDK version.

**Comment by mcatta** [comment]
Thank you for your help, It works great!
