### ISSUE TITLE
AndroidRuntimeException: android.content.pm.PackageManager$NameNotFoundException: com.google.android.webview

### ISSUE THREAD

**Issue by jaroslavhavelik** [adform/adform-tracking-android-sdk#17]
Hi,
we are recently experiencing a bug within our clients' app. It does not happen often but sometimes it does.

The last occurrence is on older devices: Brand: Samsung, Model: Galaxy Xcover3 with old OS: Version: 5.1.1. It has probably something to do with old version of google play services, but I cannot be sure. Any advice for preventing this issue? Or advice for fix?
We are using adform version 2.4.0.

```
Caused by android.util.AndroidRuntimeException: android.content.pm.PackageManager$NameNotFoundException: com.google.android.webview
       at android.webkit.WebViewFactory.getFactoryClass(WebViewFactory.java:174)
       at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:109)
       at android.webkit.WebView.getFactory(WebView.java:2194)
       at android.webkit.WebView.ensureProviderCreated(WebView.java:2189)
       at android.webkit.WebView.setOverScrollMode(WebView.java:2248)
       at android.view.View.<init>(View.java:3715)
       at android.view.View.<init>(View.java:3811)
       at android.view.ViewGroup.<init>(ViewGroup.java:503)
       at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:55)
       at android.webkit.WebView.<init>(WebView.java:544)
       at android.webkit.WebView.<init>(WebView.java:489)
       at android.webkit.WebView.<init>(WebView.java:472)
       at android.webkit.WebView.<init>(WebView.java:459)
       at android.webkit.WebView.<init>(WebView.java:449)
       at com.adform.adformtrackingsdk.web.AdWebView.<init>(AdWebView.java)
       at com.adform.adformtrackingsdk.AdformTrackingSdk.getWebView(AdformTrackingSdk.java)
       at com.adform.adformtrackingsdk.AdformTrackingSdk.loadHandler(AdformTrackingSdk.java)
       at com.adform.adformtrackingsdk.AdformTrackingSdk.startTracking(AdformTrackingSdk.java)
       at com.adform.adformtrackingsdk.AdformTrackingSdk.startTracking(AdformTrackingSdk.java)
```

**Comment by rprunskas** [comment]
Hi,
It's webview initialization bug, to solve this we added exception catching. It will no longer crash your app, but if webview fails to initialize AdformTrackingSDK won't be working as expected. Please update to 2.4.2. Thanks for reporting issue.
