### ISSUE TITLE
Crash: NetworkUtils.java line 74

### ISSUE THREAD

**Issue by areschoug** [adform/adform-tracking-android-sdk#18]
Crashlytics has reported some crashes that seems to be related to your framework:
```
Fatal Exception: java.lang.SecurityException: getDataNetworkTypeForSubscriber
       at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
       at android.os.Parcel.createException(Parcel.java:2357)
       at android.os.Parcel.readException(Parcel.java:2340)
       at android.os.Parcel.readException(Parcel.java:2282)
       at com.android.internal.telephony.ITelephony$Stub$Proxy.getNetworkTypeForSubscriber(ITelephony.java:8762)
       at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:3021)
       at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:2985)
       at com.adform.adformtrackingsdk.utils.NetworkUtils.getCurrentNetworkStatus(NetworkUtils.java:74)
       at com.adform.adformtrackingsdk.utils.NetworkUtils.getOpenRTBConnectionStatus(NetworkUtils.java:53)
       at com.adform.adformtrackingsdk.web.NetworkLoader.createDeviceData(NetworkLoader.java:109)
       at com.adform.adformtrackingsdk.web.NetworkLoader.load(NetworkLoader.java:68)
       at com.adform.adformtrackingsdk.services.SendService.startingSend(SendService.java:112)
       at com.adform.adformtrackingsdk.services.SendService$2.run(SendService.java:149)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7660)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
``` 
       
We weren't fully up to date. We used `2.1.0` so that issue might be fixed already? I haven't been able to reproduce it myself.

Let me know if you want anything from us!

**Comment by rprunskas** [comment]
It was fixed in 2.3.1 Adform Tracking SDK version, please update.
