### ISSUE TITLE
Resource leak

### ISSUE THREAD

**Issue by Wrywulf** [adform/adform-tracking-android-sdk#2]
Version:
    compile 'com.adform.tracking.sdk:adform-tracking-sdk:0.2.6'

When running the app with StrictMode enabled, it is apparent that a leak is present. This happens on a regular basis (several times during basic usage of the app):

```
...
             StrictMode  E  A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
                         E  java.lang.Throwable: Explicit termination method 'close' not called
                         E      at dalvik.system.CloseGuard.open(CloseGuard.java:184)
                         E      at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:271)
                         E      at com.android.okhttp.Connection.upgradeToTls(Connection.java:197)
                         E      at com.android.okhttp.Connection.connect(Connection.java:151)
                         E      at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:276)
                         E      at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:211)
                         E      at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:373)
                         E      at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:323)
                         E      at com.android.okhttp.internal.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:190)
                         E      at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
                         E      at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:25)
                         E      at com.adform.adformtrackingsdk.web.AdWebView.updateJs(AdWebView.java:95)
                         E      at com.adform.adformtrackingsdk.web.AdWebView.access$000(AdWebView.java:33)
                         E      at com.adform.adformtrackingsdk.web.AdWebView$AdWebViewClient.shouldInterceptRequest(AdWebView.java:71)
                         E      at android.webkit.WebViewClient.shouldInterceptRequest(WebViewClient.java:125)
                         E      at com.adform.adformtrackingsdk.web.AdWebView$AdWebViewClient.shouldInterceptRequest(AdWebView.java:65)
                         E      at com.android.webview.chromium.WebViewContentsClientAdapter.shouldInterceptRequest(WebViewContentsClientAdapter.java:297)
                         E      at org.chromium.android_webview.AwContents$BackgroundThreadClientImpl.shouldInterceptRequest(AwContents.java:465)
                         E      at org.chromium.android_webview.AwContentsBackgroundThreadClient.shouldInterceptRequestFromNative(AwContentsBackgroundThreadClient.java:38)
             System.err  W  StrictMode VmPolicy violation with POLICY_DEATH; shutting down.
...
```

It basically prevents us from enforcing StrictMode in our debug app.

**Comment by chris6647** [comment]
I experience the same issue. Here is another slightly different log:

```
E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
     java.lang.Throwable: Explicit termination method 'end' not called
         at dalvik.system.CloseGuard.open(CloseGuard.java:180)
         at java.util.zip.Inflater.<init>(Inflater.java:82)
         at com.android.okhttp.okio.GzipSource.<init>(GzipSource.java:62)
         at com.android.okhttp.internal.http.HttpEngine.unzip(HttpEngine.java:645)
         at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:827)
         at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:439)
         at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:384)
         at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:231)
         at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
         at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java)
         at com.adform.adformtrackingsdk.web.AdWebView.updateJs(AdWebView.java:95)
         at com.adform.adformtrackingsdk.web.AdWebView.access$000(AdWebView.java:33)
         at com.adform.adformtrackingsdk.web.AdWebView$AdWebViewClient.shouldInterceptRequest(AdWebView.java:71)
         at android.webkit.WebViewClient.shouldInterceptRequest(WebViewClient.java:155)
         at com.adform.adformtrackingsdk.web.AdWebView$AdWebViewClient.shouldInterceptRequest(AdWebView.java:65)
         at com.android.webview.chromium.WebViewContentsClientAdapter.shouldInterceptRequest(WebViewContentsClientAdapter.java:297)
         at org.chromium.android_webview.AwContents$BackgroundThreadClientImpl.shouldInterceptRequest(AwContents.java:465)
         at org.chromium.android_webview.AwContentsBackgroundThreadClient.shouldInterceptRequestFromNative(AwContentsBackgroundThreadClient.java:38)
W/System.err: StrictMode VmPolicy violation with POLICY_DEATH; shutting down.
```

Version:
compile 'com.adform.tracking.sdk:adform-tracking-sdk:0.2.6'

**Comment by Mindulis** [comment]
Hi,
we are looking into this issue and will inform you as soon there will be some news.

**Comment by Mindulis** [comment]
Hi,
we released fix for this issue, so please update your SDK version.
