### ISSUE TITLE
Utils.getAttributionId ANR

### ISSUE THREAD

**Issue by giovanniPolatoO** [adform/adform-tracking-android-sdk#22]
Hi,
From Firebase Crashlitics of my project a receive multiple reports regarding "ANR triggered by thread waiting for a binder transaction" in the getAttributionId function of the Utils class, more specifically line 30.

Can you perform a fix or advise me how to proceed?

Thank you very much.

**Comment by rolandasito** [comment]
Hi, could you provide full ANR report?

**Comment by giovanniPolatoO** [comment]
`main (native):tid=1 systid=12399 
#00 pc 0x9b0d0 libc.so (__ioctl + 8)
#01 pc 0x695c7 libc.so (ioctl + 26)
#02 pc 0x3a9d3 libbinder.so (android::IPCThreadState::talkWithDriver(bool) + 238)
#03 pc 0x3b8e5 libbinder.so (android::IPCThreadState::waitForResponse(android::Parcel*, int*) + 32)
#04 pc 0x3b6c7 libbinder.so (android::IPCThreadState::transact(int, unsigned int, android::Parcel const&, android::Parcel*, unsigned int) + 122)
#05 pc 0x36227 libbinder.so (android::BpBinder::transact(unsigned int, android::Parcel const&, android::Parcel*, unsigned int) + 98)
#06 pc 0xcbdf3 libandroid_runtime.so (android_os_BinderProxy_transact(_JNIEnv*, _jobject*, int, _jobject*, _jobject*, int) + 82)
       at android.os.BinderProxy.transactNative(Native method)
       at android.os.BinderProxy.transact(BinderProxy.java:605)
       at android.content.ContentProviderProxy.query(ContentProviderNative.java:470)
       at android.content.ContentResolver.query(ContentResolver.java:1204)
       at android.content.ContentResolver.query(ContentResolver.java:1125)
       at android.content.ContentResolver.query(ContentResolver.java:1081)
       at com.adform.adformtrackingsdk.utils.Utils.getAttributionId(Utils.java:30)
       at com.adform.adformtrackingsdk.entities.DefaultParameters.populateDefaultParameters(DefaultParameters.java:53)
       at com.adform.adformtrackingsdk.web.NetworkLoader.load(NetworkLoader.java:73)
       at com.adform.adformtrackingsdk.services.SendService.startingSend(SendService.java:121)
       at com.adform.adformtrackingsdk.services.SendService$2.run(SendService.java:159)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8625)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)`

**Comment by rolandasito** [comment]
We will fix this in near future. At the moment you could turn off "Facebook attribution id tracking" if you don't need it.

[Facebook attribution id tracking](https://github.com/adform/adform-tracking-android-sdk#enabledisable-facebook-attribution-id-tracking)

**Comment by rolandasito** [comment]
Moved Facebook attribution id getting to the background thread - Adform Tracking SDK 2.5.3.
