### ISSUE TITLE
Could not initialize SDK from background thread

### ISSUE THREAD

**Issue by gotev** [adform/adform-tracking-android-sdk#7]
Hi, using AdForm `1.2.0` on Android 8, in an attempt to reduce initial app loading time, I moved the following statements:

```kotlin
AdformTrackingSdk.startTracking(context, trackingID)
AdformTrackingSdk.setHttpsEnabled(true)
```
into an `IntentService`, but then my app crashes and I get the following stack trace

```java
    java.lang.IllegalStateException: Calling View methods on another thread than the UI thread.
        at com.android.webview.chromium.WebViewChromium.b(PG:115)
        at com.android.webview.chromium.WebViewChromium.c(PG:117)
        at com.android.webview.chromium.WebViewChromium.init(PG:45)
        at android.webkit.WebView.<init>(WebView.java:651)
        at android.webkit.WebView.<init>(WebView.java:581)
        at android.webkit.WebView.<init>(WebView.java:564)
        at android.webkit.WebView.<init>(WebView.java:551)
        at android.webkit.WebView.<init>(WebView.java:541)
        at com.adform.adformtrackingsdk.web.AdWebView.<init>(AdWebView.java:36)
        at com.adform.adformtrackingsdk.web.NetworkLoader.<init>(NetworkLoader.java:50)
        at com.adform.adformtrackingsdk.services.SendService.<init>(SendService.java:35)
        at com.adform.adformtrackingsdk.MainHandler.onStart(MainHandler.java:106)
        at com.adform.adformtrackingsdk.general.AbstractHandler.startTracking(AbstractHandler.java:69)
        at com.adform.adformtrackingsdk.AdformTrackingSdk.startTracking(AdformTrackingSdk.java:57)
        at com.adform.adformtrackingsdk.AdformTrackingSdk.startTracking(AdformTrackingSdk.java:38)
```
because it seems AdForm SDK does something with WebView, which could not be initialized from a background thread. Other tracking solutions are used in the same app, but they all play nice being initialized from a background thread. Is there a way to make AdForm initializable from a background thread, too?

Thank you 😉

**Comment by andriusmisiunas** [comment]
Hello,

We see this more as a feature request and will discuss internally. Will let you know about the plans in near future.

Question in the mean time - does a reasonable workaround/approach exist to overcome the issue?

**Comment by gotev** [comment]
We currently initialize it on the main thread and it works, but it will be better to offload that in the background

**Comment by svabas** [comment]
The feature will be enabled with the upcoming version. ETA - end of July 2020

**Comment by gotev** [comment]
Great!
